name = "edge-optimize-router"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[observability]
enabled = true

routes = [
  { pattern = "*your-domain.com/*", zone_name = "your-domain.com" }
]

[vars]
EDGE_OPTIMIZE_TARGET_HOST = "Enter the hostname this Worker should route to"
